on: [push] # push 操作执行自动化

jobs: # 任务
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # 要使用此仓库的私有操作，必须检出仓库（未发布的actions，需要用actions/checkout）
      # 此操作会重新拉取仓库
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        id: hello123
        # uses: actions/hello-world-javascript-action@v1
        uses: ./ # 引入使用自定义的脚本,相对路径为私有操作，非第三方引用
        with:
          who-to-greet: "测试"
      # Use the output from the `hello` step
      - name: 获取输出时间
        run: echo "时间是 ${{ steps.hello123.outputs.time }}"
